version: 2
jobs:
  build:
    working_directory: /go/src/github.com/ivanizag/apple2
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: go get -d ./...
      - run: go test . ./core6502
