version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: sudo apt install libsdl2-dev
      - run: go get -d ./...
      - run: go test ./...
